# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: http://introfall2018.dlarts.xyz
baseurl: /
title: 'Digital Language Art I'
author: Qianxun Chen
email: qianxun_chen@brown.edu
description: ''
permalink: pretty
# logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Posts: /posts/
  Students: /students/
  # Presentations: /presentations/
  Resources: /resources/
  Questions: /questions/
  Search: /search/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
# collections:
#   posts:
#     title: Posts
#     output: true
#     description: "My thoughts and ideas"
#     feature_text: |
#       Welcome to my blog
#     feature_image: "https://picsum.photos/2560/600?image=866"
